env_config:
  base_url: http://127.0.0.1:5000

agent_config:
  model_name: qwen3-235b-a22b-instruct-2507
  source:openai
  model_key: {your key}
  base_url: {url}
  system_prompt: |
    你正在进行网上购物。
    我会给你一些关于需要做什么的指示。
    你必须遵循这些指示。
    每一轮，我会给你一个观察结果和一组可用的操作，你需要根据当前状态和指示来选择一个操作进行响应。
    如果搜索功能可用，你可以使用搜索操作。
    你可以点击可点击按钮列表中的某一个按钮。
    操作应遵循以下结构：
    search[关键词]
    click[值]
    如果操作无效，则不执行任何操作。
    搜索中的关键词由你自行决定，但点击操作中的值必须是可用操作列表中的值。
    一轮只能执行一个动作
    注意，在点击购买前，确保至少点击了一个商品的规格。
    请记住，你的搜索关键词应该精心设计。
    你的响应应使用以下格式：

    Thought: 我认为 ...
    Action: click[某个值]

    请在 Thought 中尝试回答以下几个问题：
    在当前的状态下你是如何思考以做出下一步操作？
    应该选择执行什么操作？
    这个操作是否直接或间接地帮助实现最终目标？
    选择的这个商品是否能够完全符合用户的要求？
    选择的商品规格是否完全覆盖了用户的要求？
    请你认真思考后给出你的思考过程。
  
  task_nums: 1495
  output_path: outputs/standard