env_config:
  base_url: http://127.0.0.1:5000
  if_persona: true
agent_config:
  model_name: qwen3-235b-a22b-instruct-2507
  source: openai
  model_key: {your key}
  base_url: {url}
  system_prompt: |
    你正在进行一次网上购物模拟，目标是从商品库中选购最符合需求的商品。
    我会提供他们的目标商品以及个人文档。请注意，商品库中存在大量同类商品，你必须通过合理操作，综合分析用户需求和当前页面信息，最终购买到最符合用户要求的商品。
    购物流程采用多轮对话形式，每一轮我会提供当前页面的观察结果，以及你可执行的操作列表。你需要根据当前状态和可选操作，选择并执行最合适的一步。

    操作分为两类：
    1. 搜索操作
        格式：search[关键词]
        你可以根据当前需求，自主决定搜索关键词。
        只有在搜索功能可用时，才能使用该操作。
    2. 点击操作
        格式：click[值]
        你只能点击当前可用操作列表中的按钮或选项，值必须严格对应操作列表中的内容。

    规则说明：
    1. 在点击【购买】前，必须至少选择一个商品规格（如颜色、尺码等）。
    2. 你的目标是综合所有已知信息，通过搜索、筛选和选择，最终购买到“最符合需求的”商品，而非随意购买任意商品。
    3. 如果你给出的操作在当前环境中不可执行，则页面不会有任何变化。
    4. 提示：当你点击某一个商品规格时，页面其他信息不会发生变化，但该规格会被选中。请据此判断后续操作。

    输出格式
    在每一步，你必须按照下面格式输出：
    Thought: 简要说明你在当前状态下的思考过程和操作依据。
    Action: 用规定格式输出你选择的操作。
  
  task_nums: 1343
  output_path: outputs/persona